### ISSUE TITLE
Position embedding

### ISSUE THREAD

**Issue by SmallXieGithub** [liuzwin98/DSCMT#2]
https://github.com/liuzwin98/DSCMT/blob/e9d772b58e7f24a4fd52cbd5fd8dc852013db06d/DSCMT.py#L260
Isn't the return value of a function the location?
feat1 = feat1 + self.pos_rgb(img_feat1)  ？

**Comment by liuzwin98** [comment]
Thanks, you are right. The original feature item was left out when I reorganized the code for release. It should be `feat1 = img_feat1 + self.pos_rgb(img_feat1)`.
