### ISSUE TITLE
Normalization problem

### ISSUE THREAD

**Issue by SmallXieGithub** [liuzwin98/DSCMT#3]
Hello, should RGBDiff need to be normalized?
https://github.com/liuzwin98/DSCMT/blob/895f4d5181666ac30c85326e972e03fd83a5ab10/main.py#L86
https://github.com/liuzwin98/DSCMT/blob/895f4d5181666ac30c85326e972e03fd83a5ab10/DSCMT.py#L367

**Comment by liuzwin98** [comment]
Please refer to the paper TSN and its codebase for more detail.  I didn't use the RGBDiff modality.
