### ISSUE TITLE
How did you stack the two flow images?

### ISSUE THREAD

**Issue by wangwen39** [liuzwin98/DSCMT#4]
When I used denseflow toolbox to extract optical flows, I can get "flow_x_%05d.png" and "flow_y_%05d.png", two directions of optical flow fields.
Each of them with shape:[H, W]
So can you tell me how did you stack the two flow images, and save it into one image?

**Comment by liuzwin98** [comment]
Please refer to  [DenseFlow](https://github.com/open-mmlab/denseflow) for detail. There is a parameter that controls the form of output, which seems to be `step`. But I don't remember it clearly.

**Comment by wangwen39** [comment]
@liuzwin98 Thank so much for your reply. 
I have tried and it is the param of " --saveType ". 
when setting it to "png", we can got single flow image.
