### ISSUE TITLE
About PKUMMD dataset for action recognition

### ISSUE THREAD

**Issue by wangwen39** [liuzwin98/DSCMT#5]
I knotice that videos in PKUMMD dataset are all untrimmed videos, and this dataset is set for action detection task, so I wonder how did you use this dataset for action recognition? Moreover, Did you also use the TSNDataset (https://github.com/liuzwin98/DSCMT/blob/main/dataset.py#L25) for PKUMMD? 
If not, could you please share the details. Thanks so much!

Looking forward to your reply~
Best regards

**Comment by liuzwin98** [comment]
Crop the action clips from the PKU-MMD dataset's long videos and labels, and then save them as short videos for each action. Note that some of the actions in the long video have incorrect labels and need to be removed, such as the start frame of an action being later than the end frame.
