### ISSUE TITLE
关于NTU120的原始RGB视频

### ISSUE THREAD

**Issue by 24012401** [liuzwin98/DSCMT#6]
请问作者是如何将原始RGB视频转换成jpg图像的呢？因为我在官网上下载的NTU120关于RGB的是原始数据是视频，不知道作者是怎么进行转换的？或者是从哪里找到的别的数据？

**Comment by liuzwin98** [comment]
You can extract frames from the raw videos through `ffmpeg `or `opencv`, and save them to a new directory.

**Comment by 24012401** [comment]
Thank you for your reply, it was very helpful!
