### ISSUE TITLE
About the Validation Sets

### ISSUE THREAD

**Issue by 24012401** [liuzwin98/DSCMT#7]
I would like to ask you, author, about how you assign the validation set? I didn't find anything about it in your code. If it's something I didn't find, could you please tell me about the part of your code about validation set assignment. Or could you please tell me how I can set the validation set?
Also, since the dataset of NTU120 is so big, I want to train only a representative part of it, if you know which part of the data is representative, please do not hesitate to tell me.
Thank you very much for your help!

**Comment by liuzwin98** [comment]
Following the dataset's evaluation protocols, I have only split it into training and testing subsets using the scripts in the `tools `folder. Please refer to the ["NTU 120" paper](https://ieeexplore.ieee.org/abstract/document/8713892/) for more details. If you don't want to use the entire dataset, you might consider trying the ["NTU 60" dataset](https://openaccess.thecvf.com/content_cvpr_2016/html/Shahroudy_NTU_RGBD_A_CVPR_2016_paper.html).

**Comment by 24012401** [comment]
Ok then, thanks for the reply!
